### ISSUE TITLE
建议进行分类

### ISSUE THREAD

**Issue by yujiangshui** [dailyNode/node-daily#1]
如果根据某些维度对文章进行分类就更好了。

比如根据内容深浅程度或者内容类型（是提高综合编程能力 or 针对某业务的实现方法）。

**Comment by zhangyaochun** [comment]
@yujiangshui  新年快乐哈，第一遍的梳理终于出来了，欢迎再提意见哈

**Comment by yujiangshui** [comment]
@zhangyaochun 看到了，赞，同乐同乐，持续关注 ^_^
